development:
  adapter: postgresql
  encoding: unicode
  database: rails_db
  pool: 5
  username: sergeyivanes
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rails_db
  pool: 5
  username: sergeyivanes
  password:

cucumber:
  <<: *test